// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          uint         `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Code        string       `gorm:"column:code;type:text;not null;uniqueIndex:idx_roles_code,priority:1" json:"code"`
	Name        string       `gorm:"column:name;type:text;not null" json:"name"`
	Description string       `gorm:"column:description;type:text" json:"description"`
	CreatedAt   time.Time    `gorm:"column:created_at;type:datetime" json:"createdAt"`
	UpdatedAt   time.Time    `gorm:"column:updated_at;type:datetime" json:"updatedAt"`
	Permissions []Permission `gorm:"many2many:role_permissions;" json:"permissions,omitempty"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
