// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	ID          uint      `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Code        string    `gorm:"column:code;type:text;not null;uniqueIndex:idx_permissions_code,priority:1" json:"code"`
	Name        string    `gorm:"column:name;type:text;not null" json:"name"`
	Group       string    `gorm:"column:group;type:text;not null" json:"group"`
	Description string    `gorm:"column:description;type:text" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime" json:"updatedAt"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
