// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           uint       `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Email        string     `gorm:"column:email;type:text;not null;uniqueIndex:idx_users_email,priority:1" json:"email"`
	Name         string     `gorm:"column:name;type:text;not null" json:"name"`
	PasswordHash string     `gorm:"column:password_hash;type:text;not null" json:"-"`
	Status       UserStatus `gorm:"column:status;type:text;not null;default:enabled" json:"status"`
	CreatedAt    time.Time  `gorm:"column:created_at;type:datetime" json:"createdAt"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;type:datetime" json:"updatedAt"`
	Roles        []Role     `gorm:"many2many:user_roles;" json:"roles,omitempty"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
